sphinx:
  config:
    thebe_config:
      always_activate: false
      repository_url: "https://github.com/oscarrepez/Manual-de-practicas-Calculo-1"
      repository_branch: "main"
      selector: ".thebe,.cell"


launch_buttons:
  thebe: true
  binderhub_url: "https://mybinder.org" # O tu propia instancia de Binder
